version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - '80:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - '3001:3001'
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
