create table person (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL ,
	last_name VARCHAR(50) NOT NULL ,
	email VARCHAR(100) NOT NULL ,
	gender VARCHAR(20) NOT NULL ,
	date_of_birth DATE NOT NULL ,
	country VARCHAR(50)
);
insert into users (user_username, user_password, user_email, user_first_name, user_last_name, user_is_admin, user_is_active) values ('lepygargue', '1234', 'lepygargue@gmail.com', 'Thierry', 'Maurouzel', true, true);
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Mahalia', 'Sim', 'msim1@twitpic.com', 'Female', '1986-08-24', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Correy', 'Crossdale', 'ccrossdale2@wufoo.com', 'Female', '1963-08-13', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Merrill', 'Suttling', 'msuttling3@bing.com', 'Female', '1956-12-17', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Blake', 'Anfonsi', 'banfonsi4@technorati.com', 'Female', '1982-04-28', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Edmund', 'Breese', 'ebreese5@discovery.com', 'Male', '1982-04-16', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Purcell', 'Neillans', 'pneillans6@moonfruit.com', 'Male', '1976-09-18', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Jacqueline', 'Jeenes', 'jjeenes7@mozilla.com', 'Female', '1957-09-17', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Maddie', 'Wearing', 'mwearing8@google.ru', 'Male', '1966-02-19', 'Equatorial Guinea');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Karna', 'McGettigan', 'kmcgettigan9@japanpost.jp', 'Female', '1976-06-28', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Danyelle', 'Saipy', 'dsaipya@illinois.edu', 'Female', '1975-07-24', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Katharine', 'Dykins', 'kdykinsb@moonfruit.com', 'Female', '1994-05-09', 'Cameroon');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Elnore', 'Yong', 'eyongc@state.tx.us', 'Female', '1979-04-12', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Dorene', 'Tumbelty', 'dtumbeltyd@artisteer.com', 'Female', '1952-03-19', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Finlay', 'Cymper', 'fcympere@tamu.edu', 'Male', '1988-12-17', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Vinny', 'Yannikov', 'vyannikovf@zdnet.com', 'Male', '1978-01-12', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Noni', 'Sings', 'nsingsg@alibaba.com', 'Non-binary', '1982-07-21', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Magdaia', 'Petschelt', 'mpetschelth@networksolutions.com', 'Female', '1961-06-03', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Edie', 'Lound', 'eloundi@accuweather.com', 'Female', '1974-01-16', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Borden', 'Gaffer', 'bgafferj@ucoz.ru', 'Male', '1987-02-04', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Sully', 'Sisland', 'ssislandk@discuz.net', 'Male', '1950-02-27', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Melonie', 'Bain', 'mbainl@cbsnews.com', 'Female', '1983-09-07', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Orelee', 'Walthall', 'owalthallm@spotify.com', 'Female', '1989-08-12', 'Equatorial Guinea');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nickola', 'Carnelley', 'ncarnelleyn@spotify.com', 'Male', '1973-04-17', 'Venezuela');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Walsh', 'Athelstan', 'wathelstano@imgur.com', 'Male', '1965-09-11', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Amalea', 'North', 'anorthp@stanford.edu', 'Female', '1955-11-24', 'Qatar');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Emile', 'Novak', 'enovakq@rediff.com', 'Male', '1971-10-10', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Olimpia', 'Zupa', 'ozupar@nih.gov', 'Female', '1981-12-14', 'Netherlands');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Shela', 'Lindenstrauss', 'slindenstrausss@indiegogo.com', 'Female', '1966-09-27', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Silvano', 'Sikorsky', 'ssikorskyt@java.com', 'Male', '1978-09-02', 'Norway');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ansley', 'Glacken', 'aglackenu@statcounter.com', 'Female', '1986-09-17', 'Chad');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Alonso', 'Dunham', 'adunhamv@nytimes.com', 'Male', '1955-09-08', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Traci', 'Tace', 'ttacew@bigcartel.com', 'Female', '1990-11-14', 'Nigeria');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Amalie', 'Starr', 'astarrx@marketwatch.com', 'Genderqueer', '1965-10-26', 'Serbia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Mia', 'Dando', 'mdandoy@hatena.ne.jp', 'Female', '1953-07-08', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Rhiamon', 'O''Sheerin', 'rosheerinz@last.fm', 'Female', '1964-03-29', 'Mexico');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Shay', 'Simonsen', 'ssimonsen10@ocn.ne.jp', 'Male', '1981-11-08', 'Tanzania');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Giacopo', 'Tootin', 'gtootin11@hubpages.com', 'Male', '1991-09-29', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Charlotte', 'Chasmor', 'cchasmor12@freewebs.com', 'Female', '1984-09-23', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Berna', 'Greystock', 'bgreystock13@merriam-webster.com', 'Female', '1986-11-01', 'Gabon');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Janaye', 'Mattingly', 'jmattingly14@uiuc.edu', 'Female', '1955-10-06', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Emile', 'Ragdale', 'eragdale15@hc360.com', 'Male', '1950-04-15', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Sammie', 'Roake', 'sroake16@webs.com', 'Male', '1954-11-04', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Chen', 'Isitt', 'cisitt17@usa.gov', 'Male', '1973-06-19', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Allyn', 'Kilfether', 'akilfether18@geocities.jp', 'Female', '2001-07-12', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Callean', 'Aicken', 'caicken19@tripod.com', 'Male', '1979-09-26', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Gary', 'Hallett', 'ghallett1a@oakley.com', 'Male', '1973-10-24', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Billy', 'Wardley', 'bwardley1b@bloglines.com', 'Male', '1971-12-21', 'Czech Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Noby', 'Dorre', 'ndorre1c@ed.gov', 'Male', '2002-11-21', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Eachelle', 'Mertgen', 'emertgen1d@rediff.com', 'Female', '1963-05-17', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Marna', 'Bravington', 'mbravington1e@de.vu', 'Female', '1987-08-05', 'Bosnia and Herzegovina');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Florence', 'Cawthorn', 'fcawthorn1f@prlog.org', 'Female', '1993-04-28', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Artemus', 'Duley', 'aduley1g@ovh.net', 'Male', '1981-12-12', 'Uganda');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Zena', 'Bare', 'zbare1h@google.es', 'Female', '1964-09-29', 'Kazakhstan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Odille', 'Buncom', 'obuncom1i@goo.gl', 'Female', '1998-09-21', 'Chad');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Humfried', 'Elwyn', 'helwyn1j@photobucket.com', 'Male', '1988-03-08', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Brantley', 'Quinlan', 'bquinlan1k@nasa.gov', 'Male', '1990-09-23', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Salem', 'Climson', 'sclimson1l@yale.edu', 'Male', '1974-04-19', 'Tunisia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Raquel', 'Claque', 'rclaque1m@people.com.cn', 'Female', '1999-10-24', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Fraser', 'Allston', 'fallston1n@japanpost.jp', 'Bigender', '1975-10-16', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Fulvia', 'Tutchell', 'ftutchell1o@clickbank.net', 'Female', '1973-09-30', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Gizela', 'Dockwray', 'gdockwray1p@chronoengine.com', 'Female', '1983-05-25', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Maxwell', 'McGettigan', 'mmcgettigan1q@mlb.com', 'Male', '1986-08-16', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ulrike', 'McArtan', 'umcartan1r@cdbaby.com', 'Female', '1968-11-13', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Lyell', 'McEllen', 'lmcellen1s@freewebs.com', 'Male', '1955-10-21', 'Burkina Faso');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Freddie', 'Follin', 'ffollin1t@etsy.com', 'Male', '1972-03-17', 'Latvia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Raoul', 'Piesold', 'rpiesold1u@wufoo.com', 'Male', '1954-01-25', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Wandie', 'Meriel', 'wmeriel1v@free.fr', 'Genderqueer', '1984-09-27', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Layne', 'Kerrich', 'lkerrich1w@hugedomains.com', 'Female', '1967-03-15', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Bryn', 'Hickinbottom', 'bhickinbottom1x@surveymonkey.com', 'Female', '1978-07-10', 'Nigeria');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Sonny', 'Jenkison', 'sjenkison1y@biglobe.ne.jp', 'Male', '1973-06-19', 'Armenia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Fabe', 'Purkess', 'fpurkess1z@usatoday.com', 'Male', '1998-08-02', 'Netherlands');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Haskell', 'Lindwall', 'hlindwall20@shinystat.com', 'Male', '1968-01-04', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Margit', 'Schapero', 'mschapero21@businesswire.com', 'Female', '1962-09-02', 'Pakistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Albertina', 'Dunbar', 'adunbar22@nhs.uk', 'Female', '1954-09-04', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Arline', 'Collingham', 'acollingham23@altervista.org', 'Female', '1962-07-07', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Dwain', 'Piercy', 'dpiercy24@unblog.fr', 'Bigender', '1961-07-04', 'Serbia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Winonah', 'Simenon', 'wsimenon25@diigo.com', 'Female', '1973-02-16', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Norris', 'Worland', 'nworland26@jalbum.net', 'Male', '1965-09-07', 'Equatorial Guinea');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nil', 'Wethers', 'nwethers27@wiley.com', 'Genderqueer', '1955-10-10', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Glynda', 'Trace', 'gtrace28@chicagotribune.com', 'Female', '1959-09-29', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nolly', 'Beincken', 'nbeincken29@drupal.org', 'Male', '1960-01-12', 'Israel');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Evania', 'Grindle', 'egrindle2a@wikia.com', 'Female', '1985-01-02', 'Canada');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Cristobal', 'Beviss', 'cbeviss2b@amazon.de', 'Male', '1959-04-11', 'Pakistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Mateo', 'Mandrake', 'mmandrake2c@mozilla.org', 'Male', '1982-08-30', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Emile', 'Flitcroft', 'eflitcroft2d@unesco.org', 'Male', '1961-06-06', 'Czech Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Oralle', 'Rangall', 'orangall2e@woothemes.com', 'Female', '1979-05-07', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Faydra', 'Gillean', 'fgillean2f@eepurl.com', 'Female', '1982-07-16', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Osbert', 'Blenkinsopp', 'oblenkinsopp2g@behance.net', 'Male', '1992-04-19', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Tandy', 'Samworth', 'tsamworth2h@umn.edu', 'Female', '1954-12-22', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Wendell', 'Deinhardt', 'wdeinhardt2i@odnoklassniki.ru', 'Male', '1985-07-25', 'Ivory Coast');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Brannon', 'Rudman', 'brudman2j@g.co', 'Male', '1980-03-09', 'Ukraine');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Estella', 'Niesing', 'eniesing2k@cdc.gov', 'Female', '1969-09-28', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Risa', 'Blaksley', 'rblaksley2l@list-manage.com', 'Female', '2002-01-18', 'Saudi Arabia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Fair', 'Gimert', 'fgimert2m@wufoo.com', 'Male', '1997-01-13', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Milena', 'Darlaston', 'mdarlaston2n@clickbank.net', 'Female', '1984-10-29', 'Argentina');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nata', 'Perel', 'nperel2o@discuz.net', 'Female', '1999-12-19', 'Peru');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Manny', 'Purcer', 'mpurcer2p@devhub.com', 'Male', '1958-06-01', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Zachariah', 'Busen', 'zbusen2q@arstechnica.com', 'Male', '1960-08-27', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Jock', 'Keasley', 'jkeasley2r@wsj.com', 'Male', '1967-01-10', 'Indonesia');
